# Generated by Django 5.2 on 2025-04-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitob',
            options={'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='kutubxonachi',
            options={'verbose_name': 'Kutubxonachi', 'verbose_name_plural': 'Kutubxonachilar'},
        ),
        migrations.AlterModelOptions(
            name='muallif',
            options={'verbose_name': 'Muallif', 'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Recordlar'},
        ),
        migrations.AlterModelOptions(
            name='talaba',
            options={'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
    ]
